version: '3.8'
services:
  app:
    image: my-spring-boot-app
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/library
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Ruslan2002
    depends_on:
      - db
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ruslan2002
    ports:
      - "5432:5432"
